### ISSUE TITLE
 The Repository structure is not as required.

### ISSUE THREAD

**Issue by pushpdeep** [cybersquad04/getting-started#1]
The Repository structure is not as required.

Please refer this structure here and correct it ASAP.

the repository structure -
http://vlabs.iitb.ac.in/gitlab/Community-Docs/New-Lab-development/Round-templates

Documentation on porting of the experiment -
https://docs.google.com/document/d/1y8M1qslLjtyHmGnjclJQVEscNnB2n2JJTpeIADiuSkk/edit?usp=sharing
@cybersquad04

**Comment by cybersquad04** [comment]
Resolved

**Comment by pushpdeep** [comment]
@cybersquad04 its still not appropriate. 
file names are not correct. 

reference the reference repo again

**Comment by cybersquad04** [comment]
Issue Resolved

**Comment by pushpdeep** [comment]
@cybersquad04  The structure is right but the content inside the pedagogy ans storyboard is missing.

**Comment by cybersquad04** [comment]
Sir we haven't used the images yet that's why we haven't created the image folders.
